name: Deploy OCI Compartment with Remote State

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Run OCI Terraform
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
    timeout-minutes: 20  # Extended timeout

    steps:
      # Step 1: Clone Repository
      - name: Clone repo
        uses: actions/checkout@v4

      # Step 2: Write OCI Config and Private Key Files
      - name: Write Config & Key Files
        run: |
          mkdir ~/.oci
          echo "[DEFAULT]" >> ~/.oci/config
          echo "user=${{ secrets.OCI_USER_OCID }}" >> ~/.oci/config
          echo "fingerprint=${{ secrets.OCI_FINGERPRINT }}" >> ~/.oci/config
          echo "region=${{ secrets.OCI_REGION }}" >> ~/.oci/config
          echo "tenancy=${{ secrets.OCI_TENANCY_OCID }}" >> ~/.oci/config
          echo "key_file=~/.oci/key.pem" >> ~/.oci/config
          echo "${{ secrets.OCI_PRIVATE_KEY_PATH }}" > ~/.oci/key.pem
          chmod 600 ~/.oci/key.pem
          chmod 600 ~/.oci/config

      # Step 3: Install OCI CLI
      - name: Install OCI CLI
        run: |
          curl -L -O https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh
          chmod +x install.sh
          ./install.sh --accept-all-defaults --oci-cli-version 3.51.5

      # Step 4: Add OCI CLI to PATH and Reload Shell
      - name: Add OCI CLI to PATH
        run: |
          echo "/home/runner/bin" >> $GITHUB_PATH
          export PATH=$PATH:/home/runner/bin
          echo "PATH updated to include OCI CLI."

      # Step 5: Validate OCI CLI Installation
      - name: Validate OCI CLI Installation
        run: |
          oci --version

      # Step 6: Fix OCI File Permissions
      - name: Fix OCI Config File Permissions
        run: |
          oci setup repair-file-permissions --file ~/.oci/config
          oci setup repair-file-permissions --file ~/.oci/key.pem

      # Step 7: Setup Terraform
      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      # Step 8: Initialize Terraform with Remote State
      - name: Terraform Init
        env:
          TF_VAR_access_key: ${{ secrets.OCI_ACCESS_KEY }}       # S3 interoperability access key
          TF_VAR_user_ocid: ${{ secrets.OCI_USER_OCID }}
          TF_VAR_fingerprint: ${{ secrets.OCI_FINGERPRINT }}
          TF_VAR_private_key_path: ${{ secrets.OCI_PRIVATE_KEY_PATH }}
          TF_VAR_region: ${{ secrets.OCI_REGION }}
          TF_VAR_tenancy_ocid: ${{ secrets.OCI_TENANCY_OCID }}
        run: terraform init

      # Step 9: Plan Terraform Changes
      - name: Terraform Plan
        env:
          TF_VAR_access_key: ${{ secrets.OCI_ACCESS_KEY }}
          TF_VAR_user_ocid: ${{ secrets.OCI_USER_OCID }}
          TF_VAR_fingerprint: ${{ secrets.OCI_FINGERPRINT }}
          TF_VAR_private_key_path: ${{ secrets.OCI_PRIVATE_KEY_PATH }}
          TF_VAR_region: ${{ secrets.OCI_REGION }}
          TF_VAR_tenancy_ocid: ${{ secrets.OCI_TENANCY_OCID }}
        run: terraform plan

      # Step 10: Apply Terraform Changes
      - name: Apply Terraform Changes
        env:
          TF_VAR_access_key: ${{ secrets.OCI_ACCESS_KEY }}
          TF_VAR_user_ocid: ${{ secrets.OCI_USER_OCID }}
          TF_VAR_fingerprint: ${{ secrets.OCI_FINGERPRINT }}
          TF_VAR_private_key_path: ${{ secrets.OCI_PRIVATE_KEY_PATH }}
          TF_VAR_region: ${{ secrets.OCI_REGION }}
          TF_VAR_tenancy_ocid: ${{ secrets.OCI_TENANCY_OCID }}
        run: terraform apply -auto-approve
