name: Deploy OCI Compartment

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Run OCI Terraform
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      # Step 1: Clone Repository
      - name: Clone repo
        uses: actions/checkout@v4

      # Step 2: Write OCI Config and Private Key Files
      - name: Write Config & Key Files
        run: |
          mkdir ~/.oci
          echo "[DEFAULT]" >> ~/.oci/config
          echo "user=${{ secrets.OCI_USER_OCID }}" >> ~/.oci/config
          echo "fingerprint=${{ secrets.OCI_FINGERPRINT }}" >> ~/.oci/config
          echo "region=${{ secrets.OCI_REGION }}" >> ~/.oci/config
          echo "tenancy=${{ secrets.OCI_TENANCY_OCID }}" >> ~/.oci/config
          echo "key_file=~/.oci/key.pem" >> ~/.oci/config
          echo "${{ secrets.OCI_PRIVATE_KEY }}" > ~/.oci/key.pem
          chmod 600 ~/.oci/key.pem
          chmod 600 ~/.oci/config

      # Step 3: Install OCI CLI
      - name: Install OCI CLI
        run: |
          curl -L -O https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh
          chmod +x install.sh
          ./install.sh --accept-all-defaults --oci-cli-version 3.51.5
          echo "/home/runner/bin" >> $GITHUB_PATH
          exec -l $SHELL

      # Step 4: Fix OCI File Permissions
      - name: Fix OCI Config File Permissions
        run: |
          oci setup repair-file-permissions --file ~/.oci/config
          oci setup repair-file-permissions --file ~/.oci/key.pem

      # Step 5: Setup Terraform
      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      # Step 6: Initialize Terraform (Local Backend)
      - name: Terraform Init
        run: |
          terraform init

      # Step 7: Plan Terraform Changes
      - name: Terraform Plan
        env:
          TF_VAR_oci_private_key: ${{ secrets.OCI_PRIVATE_KEY }}
        run: |
          terraform plan

      # Step 8: Apply Terraform Changes
      - name: Apply Terraform Changes
        env:
          TF_VAR_oci_private_key: ${{ secrets.OCI_PRIVATE_KEY }}
        run: |
          terraform apply -auto-approve
